<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/09/18 18:12:06
sfConfig::add(array(
  'app_just_giving_app_key' => '5601072ab94901581afe5f75c8ac399d',
  'app_just_giving_app_id' => '50694b0a',
  'app_username' => 'dogsbody',
  'app_password' => 'trustno1',
  'app_account_create_sand' => 'https://api.staging.justgiving.com/{applicationid}/v1/account',
  'app_account_create_live' => 'https://api.justgiving.com/{applicationid}/v1/account',
  'app_account_list_all_pages_sand' => 'https://api.staging.justgiving.com/{applicationid}/v1/account/{email}/pages',
  'app_account_list_all_pages_live' => 'https://api.justgiving.com/{applicationid}/v1/account/{email}/pages',
  'app_donation_retrieve_status_sand' => 'https://api.staging.justgiving.com/{applicationid}/v1/donation/{donationId}/status',
  'app_donation_retrieve_status_live' => 'https://api.justgiving.com/{applicationid}/v1/donation/{donationId}/status',
  'app_fundraising_create_sand' => 'https://api.staging.justgiving.com/{applicationid}/v1/donation/{donationId}/status',
  'app_fundraising_create_live' => 'https://api.justgiving.com/{applicationid}/v1/donation/{donationId}/status',
  'app_fundraising_is_shortname_registered_sand' => 'https://api.staging.justgiving.com/{applicationid}/v1/fundraising/pages/{pageShortName}',
  'app_fundraising_is_shortname_registered_live' => 'https://api.justgiving.com/{applicationid}/v1/fundraising/pages/{pageShortName}',
  'app_fundraising_list_all_sand' => 'https://api.staging.justgiving.com/{applicationid}/v1/fundraising/pages',
  'app_fundraising_list_all_live' => 'https://api.justgiving.com/{applicationid}/v1/fundraising/pages',
  'app_fundraising_retrieve_donations_for_page_sand' => 'https://api.staging.justgiving.com/{applicationid}/v1/fundraising/pages/{pageShortName}/donations',
  'app_fundraising_retrieve_donations_for_page_live' => 'https://api.justgiving.com/{applicationid}/v1/fundraising/pages/{pageShortName}/donations',
  'app_fundraising_retrieve_page_sand' => 'https://api.staging.justgiving.com/{applicationid}/v1/fundraising/pages/{pageShortName}',
  'app_fundraising_retrieve_page_live' => 'https://api.justgiving.com/{applicationid}/v1/fundraising/pages/{pageShortName}',
  'app_search_charity_search_sand' => 'https://api.staging.justgiving.com/{applicationid}/v1/charity/search',
  'app_search_charity_search_live' => 'https://api.justgiving.com/{applicationid}/v1/charity/search',
));
