<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/19 01:14:11

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=charityhack',
  'username' => 'charityhack',
  'password' => 'hacktheplanet',
  'name' => 'doctrine',
)),);
