<?php

/**
 * BaseEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property decimal $total_money
 * @property Doctrine_Collection $JustGivingEvent
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method decimal             getTotalMoney()      Returns the current record's "total_money" value
 * @method Doctrine_Collection getJustGivingEvent() Returns the current record's "JustGivingEvent" collection
 * @method Event               setId()              Sets the current record's "id" value
 * @method Event               setTotalMoney()      Sets the current record's "total_money" value
 * @method Event               setJustGivingEvent() Sets the current record's "JustGivingEvent" collection
 * 
 * @package    aggreg8
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('total_money', 'decimal', 20, array(
             'type' => 'decimal',
             'length' => 20,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('JustGivingEvent', array(
             'local' => 'id',
             'foreign' => 'event_id'));
    }
}