<?php

/**
 * Basecharity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $code
 * @property varchar $name
 * 
 * @method integer getId()   Returns the current record's "id" value
 * @method varchar getCode() Returns the current record's "code" value
 * @method varchar getName() Returns the current record's "name" value
 * @method charity setId()   Sets the current record's "id" value
 * @method charity setCode() Sets the current record's "code" value
 * @method charity setName() Sets the current record's "name" value
 * 
 * @package    aggreg8
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecharity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('charity');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('code', 'varchar', 20, array(
             'type' => 'varchar',
             'length' => 20,
             ));
        $this->hasColumn('name', 'varchar', 200, array(
             'type' => 'varchar',
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}