<?php

/**
 * BasePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $title
 * @property varchar $short_name
 * @property decimal $target_amount
 * @property varchar $charity_code
 * @property varchar $charity_name
 * @property decimal $money_raised
 * @property integer $just_giving_event_id
 * @property varchar $user
 * @property JustGivingEvent $JustGivingEvent
 * 
 * @method integer         getId()                   Returns the current record's "id" value
 * @method varchar         getTitle()                Returns the current record's "title" value
 * @method varchar         getShortName()            Returns the current record's "short_name" value
 * @method decimal         getTargetAmount()         Returns the current record's "target_amount" value
 * @method varchar         getCharityCode()          Returns the current record's "charity_code" value
 * @method varchar         getCharityName()          Returns the current record's "charity_name" value
 * @method decimal         getMoneyRaised()          Returns the current record's "money_raised" value
 * @method integer         getJustGivingEventId()    Returns the current record's "just_giving_event_id" value
 * @method varchar         getUser()                 Returns the current record's "user" value
 * @method JustGivingEvent getJustGivingEvent()      Returns the current record's "JustGivingEvent" value
 * @method Page            setId()                   Sets the current record's "id" value
 * @method Page            setTitle()                Sets the current record's "title" value
 * @method Page            setShortName()            Sets the current record's "short_name" value
 * @method Page            setTargetAmount()         Sets the current record's "target_amount" value
 * @method Page            setCharityCode()          Sets the current record's "charity_code" value
 * @method Page            setCharityName()          Sets the current record's "charity_name" value
 * @method Page            setMoneyRaised()          Sets the current record's "money_raised" value
 * @method Page            setJustGivingEventId()    Sets the current record's "just_giving_event_id" value
 * @method Page            setUser()                 Sets the current record's "user" value
 * @method Page            setJustGivingEvent()      Sets the current record's "JustGivingEvent" value
 * 
 * @package    aggreg8
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('title', 'varchar', 200, array(
             'type' => 'varchar',
             'length' => 200,
             ));
        $this->hasColumn('short_name', 'varchar', 200, array(
             'type' => 'varchar',
             'length' => 200,
             ));
        $this->hasColumn('target_amount', 'decimal', 20, array(
             'type' => 'decimal',
             'length' => 20,
             'scale' => '2',
             ));
        $this->hasColumn('charity_code', 'varchar', 20, array(
             'type' => 'varchar',
             'length' => 20,
             ));
        $this->hasColumn('charity_name', 'varchar', 200, array(
             'type' => 'varchar',
             'length' => 200,
             ));
        $this->hasColumn('money_raised', 'decimal', 20, array(
             'type' => 'decimal',
             'length' => 20,
             'scale' => '2',
             ));
        $this->hasColumn('just_giving_event_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user', 'varchar', 200, array(
             'type' => 'varchar',
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('JustGivingEvent', array(
             'local' => 'just_giving_event_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}