Event:
  columns:
    id:                       { type: integer(8), primary: true, autoincrement: true }
    code:                     varchar(50)
    name:                     varchar(200)
    total_money:              decimal(20,2)
  relations:
    JustGivingEvent:
      onDelete

JustGivingEvent:
  columns:
    id:                       { type: integer(8), primary: true, autoincrement: true }
    jg_event_code:            varchar(20)
    event_id:                 integer
  relations:
    Event:
      local:                  event_id
      foreign:                id
      onDelete:               CASCADE

Page:
  columns:
    id:                       { type: integer(8), primary: true, autoincrement: true }
    title:                    varchar(200)
    short_name:               varchar(200)
    target_amount:            decimal(20,2)
    charity_code:             varchar(20)
    charity_name:             varchar(200)
    money_raised:             decimal(20,2)
    just_giving_event_id:     integer
    user:                     varchar(200)
  relations:
    JustGivingEvent:
      local:                  just_giving_event_id
      foreign:                id
      onDelete:               CASCADE

charity:
  columns:
    id:                       { type: integer(8), primary: true, autoincrement: true }
    code:                     varchar(20)
    name:                     varchar(200)
