<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/18 14:40:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=aggreg8',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
